"""empty message

Revision ID: de8bf15b6b07
Revises: 
Create Date: 2021-04-26 21:09:48.641177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8bf15b6b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fg_pct_lvl', sa.String(length=100), nullable=False),
    sa.Column('ft_pct_lvl', sa.String(length=100), nullable=False),
    sa.Column('three_pm_pct_lvl', sa.String(length=100), nullable=False),
    sa.Column('reb_lvl', sa.String(length=100), nullable=False),
    sa.Column('ast_lvl', sa.String(length=100), nullable=False),
    sa.Column('stl_lvl', sa.String(length=100), nullable=False),
    sa.Column('blk_lvl', sa.String(length=100), nullable=False),
    sa.Column('pts_lvl', sa.String(length=100), nullable=False),
    sa.Column('to_lvl', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
